version: "3.9"

services:
  gateway:
    build:
      context: ./BorsaApp.Api.Gateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  users-api:
    build:
      context: ./BorsaApp.Api.Users
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  subscription-api:
    build:
      context: ./BorsaApp.Api.Subscription
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  market-api:
    build:
      context: ./BorsaApp.Api.Market
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notification-api:
    build:
      context: ./BorsaApp.Api.Notification
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
