version: "3.9"

services:
  gateway:
    image: ghcr.io/omugulkoc/borsaapp/gateway:latest
    ports:
       - "8081:8080"
    deploy:
      replicas: 1
    networks:
      - backend

  users-api:
    image: ghcr.io/omugulkoc/borsaapp/users-api:latest
    deploy:
      replicas: 2
    networks:
      - backend

  subscription-api:
    image: ghcr.io/omugulkoc/borsaapp/subscription-api:latest
    deploy:
      replicas: 2
    networks:
      - backend

  market-api:
    image: ghcr.io/omugulkoc/borsaapp/market-api:latest
    deploy:
      replicas: 2
    networks:
      - backend

  notification-api:
    image: ghcr.io/omugulkoc/borsaapp/notification-api:latest
    deploy:
      replicas: 2
    networks:
      - backend

networks:
  backend:
    driver: overlay
